from typing import List, Protocol
from app.core.models.item import Item

class IItemService(Protocol):
    def create(self, item: Item) -> Item: ...
    def list(self) -> List[Item]: ...
    def update(self, item_id: int, item: Item) -> Item: ...
    def delete(self, item_id: int) -> None: ...
