from typing import List, Optional, Protocol
from app.core.models.item import Item

class IItemRepository(Protocol):
    def add_item(self, item: Item) -> Item: ...
    def view_items(self) -> List[Item]: ...
    def get_item(self, item_id: int) -> Optional[Item]: ...
    def update_item(self, item_id: int, item: Item) -> Optional[Item]: ...
    def delete_item(self, item_id: int) -> bool: ...